class Solution {
    public int numSubarraysWithSum(int[] nums, int goal) {
        int func1=getcount(nums,goal);
        int func2=getcount(nums,goal-1);
        return func1-func2;
        
    }
    static int getcount(int[] nums,int goal)
    {
        if(goal<0)
        {
            return 0;
        }
        int r=0;
        int l=0;
        int count=0;
        int n=nums.length;
        int sum=0;
        while(r<n)
        {
            sum=sum+nums[r];
            while(sum>goal)
            {
                sum=sum-nums[l];
                l++;
            }
            if(sum<=goal)
            {
                count=count+r-l+1;
            }
            r++;
        }
        return count;

    }
}
